-- Official melee weapons. Caliber is intentionally nullable for non-firearms.
alter table weapon_catalog modify column caliber varchar(255) null;
alter table weapon_inventory modify column caliber varchar(255) null;
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-navaja','Navaja','CUERPO_PEQUENA','PEQUENA',1,0,'x3',70,25,15,5,2,null,1,null,null,'/weapons/homogenized/melee-navaja.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-cuchillo-pequeno','Cuchillo pequeño','CUERPO_PEQUENA','PEQUENA',1,0,'x3',55,30,20,10,3,null,1,null,null,'/weapons/homogenized/melee-cuchillo-pequeno.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-cuchillo','Cuchillo','CUERPO_PEQUENA','PEQUENA',1,0,'x2',70,30,20,15,1,null,1,null,null,'/weapons/homogenized/melee-cuchillo.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-porra-extensible','Porra extensible','CUERPO_PEQUENA','PEQUENA',1,0,'x2',55,35,25,20,1,null,1,null,null,'/weapons/homogenized/melee-porra-extensible.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-porra','Porra','CUERPO_MEDIANA','MEDIANA',1,0,'x2',55,35,25,20,2,null,1,null,'Puedes reducir en 1 la localización','/weapons/homogenized/melee-porra.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-palanca','Palanca','CUERPO_MEDIANA','MEDIANA',1,0,'x2',65,35,25,20,null,null,1,null,null,'/weapons/homogenized/melee-palanca.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-bate-beisbol','Bate de béisbol','CUERPO_MEDIANA','MEDIANA',1,0,'x2',70,40,30,20,1,null,1,null,null,'/weapons/homogenized/melee-bate-beisbol.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-martillo','Martillo','CUERPO_PEQUENA','PEQUENA',1,0,'x2',75,35,20,15,null,null,1,null,null,'/weapons/homogenized/melee-martillo.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-machete','Machete','CUERPO_MEDIANA','MEDIANA',1,0,'x2',80,40,30,20,1,null,1,null,null,'/weapons/homogenized/melee-machete.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-espada','Espada','CUERPO_MEDIANA','MEDIANA',1,0,'x2',85,45,30,20,null,null,1,null,null,'/weapons/homogenized/melee-espada.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-katana','Katana','CUERPO_MEDIANA','MEDIANA',1,0,'x2',100,45,25,10,null,null,1,null,null,'/weapons/homogenized/melee-katana.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-hacha','Hacha','CUERPO_MEDIANA','MEDIANA',1,0,'x1',90,45,35,20,null,null,1,null,null,'/weapons/homogenized/melee-hacha.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-lanza','Lanza','CUERPO_PESADA','GRANDE',1,0,'x1',85,40,30,20,1,null,1,null,'+1 casilla de alcance','/weapons/homogenized/melee-lanza.jpg',true);
insert into weapon_catalog (id,name,weapon_type,size,weapon_range,reload,rate,damage_vital,damage_normal,damage_light,damage_very_light,aim,automatic_fire,capacity,caliber,extra_rule,image_url,official) values ('melee-mazo','Mazo','CUERPO_PESADA','GRANDE',1,0,'x1',95,50,35,25,null,null,1,null,null,'/weapons/homogenized/melee-mazo.jpg',true);
