package com.dexm.personajes.application;

import com.dexm.personajes.adapter.out.persistence.*;
import com.dexm.personajes.security.AuthorizationService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;

/** Versioned, portable game-data archives. Images and access-control data never enter this boundary. */
@Service
public class ArchiveService {
    public static final int FORMAT_VERSION = 1;
    private final ObjectMapper json = new ObjectMapper();
    private final CampaignRepository campaigns; private final CharacterRepository characters; private final MinorAttributeDefinitionRepository definitions;
    private final CharacterMinorAttributeValueRepository minorValues; private final CharacterAttributeModifierRepository modifiers; private final TrainingActivityRepository training;
    private final OtherInventoryItemRepository others; private final WeaponRepository weapons; private final AmmunitionRepository ammunition; private final ArmorRepository armor; private final ShieldRepository shields; private final PhysicalShieldRepository physicalShields; private final MilestoneRepository milestones;
    private final AuthorizationService authorization;

    public ArchiveService(CampaignRepository campaigns, CharacterRepository characters, MinorAttributeDefinitionRepository definitions, CharacterMinorAttributeValueRepository minorValues, CharacterAttributeModifierRepository modifiers, TrainingActivityRepository training, OtherInventoryItemRepository others, WeaponRepository weapons, AmmunitionRepository ammunition, ArmorRepository armor, ShieldRepository shields, PhysicalShieldRepository physicalShields, MilestoneRepository milestones, AuthorizationService authorization) {
        this.campaigns=campaigns; this.characters=characters; this.definitions=definitions; this.minorValues=minorValues; this.modifiers=modifiers; this.training=training; this.others=others; this.weapons=weapons; this.ammunition=ammunition; this.armor=armor; this.shields=shields; this.physicalShields=physicalShields; this.milestones=milestones; this.authorization=authorization;
    }

    public Archive exportCharacter(String id) { requireCharacterWrite(id); return new Archive(FORMAT_VERSION, "character", Instant.now().toString(), null, snapshot(characters.findById(id).orElseThrow())); }
    public Archive exportCampaign(String id) { requireAdmin(); var campaign=campaigns.findById(id).orElseThrow(); return new Archive(FORMAT_VERSION, "campaign", Instant.now().toString(), new CampaignData(campaign.getName(), definitions.findByCampaignIdOrderByNameAsc(id).stream().map(this::definition).toList(), characters.findByCampaignIdOrderByNameAsc(id).stream().map(this::snapshot).toList()), null); }

    @Transactional public void importCharacter(String destinationId, String payload) { requireCharacterWrite(destinationId); var archive=parse(payload,"character"); replaceCharacter(characters.findById(destinationId).orElseThrow(), archive.character()); }
    @Transactional public void importCampaign(String destinationId, String payload) { requireAdmin(); var archive=parse(payload,"campaign"); var target=campaigns.findById(destinationId).orElseThrow(); target.setName(archive.campaign().name()); campaigns.save(target);
        var existingBySource = new HashMap<String,CharacterEntity>(); for (var candidate:characters.findByCampaignIdOrderByNameAsc(destinationId)) existingBySource.put(candidate.getImportSourceId()==null?candidate.getId():candidate.getImportSourceId(),candidate);
        var importedCharacters = new LinkedHashMap<String,CharacterEntity>();
        for(CharacterData source:archive.campaign().characters()) { var targetCharacter=existingBySource.get(source.sourceId()); if(targetCharacter==null) { targetCharacter=new CharacterEntity(UUID.randomUUID().toString(),destinationId,source.name(),null,source.experience(),source.level(),source.attributesJson(),source.geneticsJson()); targetCharacter.setImportSourceId(source.sourceId()); characters.save(targetCharacter); } importedCharacters.put(source.sourceId(),targetCharacter); }
        var definitionIds = new HashMap<String,String>();
        for (DefinitionData source : archive.campaign().definitions()) { var existing=definitions.findByCampaignIdAndKey(destinationId,source.key()).orElse(null); var targetId=existing == null ? UUID.randomUUID().toString() : existing.getId(); definitionIds.put(source.id(),targetId); if(existing==null) { var owner=source.ownerCharacterId()==null ? null : Optional.ofNullable(importedCharacters.get(source.ownerCharacterId())).map(CharacterEntity::getId).orElse(null); definitions.save(new MinorAttributeDefinitionEntity(targetId,destinationId,owner,source.key(),source.name(),source.maxFormula(),source.bonusSource(),source.type())); } }
        for(CharacterData source:archive.campaign().characters()) replaceCharacter(importedCharacters.get(source.sourceId()),source,definitionIds);
    }

    private Archive parse(String payload,String type) { try { var archive=json.readValue(payload,Archive.class); if(archive.version()!=FORMAT_VERSION) throw new IllegalArgumentException("La versión del fichero no es compatible"); if(!type.equals(archive.type())) throw new IllegalArgumentException("El fichero no corresponde a un/a " + ("campaign".equals(type)?"campaña":"personaje")); if(("character".equals(type)&&archive.character()==null)||("campaign".equals(type)&&archive.campaign()==null)) throw new IllegalArgumentException("El fichero está incompleto"); return archive; } catch(IllegalArgumentException e){throw e;} catch(Exception e){throw new IllegalArgumentException("El fichero no es un archivo DEXM válido");} }
    private void requireAdmin(){ authorization.requireAdmin(SecurityContextHolder.getContext().getAuthentication()); }
    private void requireCharacterWrite(String id){ authorization.requireCharacter(SecurityContextHolder.getContext().getAuthentication(),id,true); }

    private CharacterData snapshot(CharacterEntity c) { return new CharacterData(c.getImportSourceId()==null?c.getId():c.getImportSourceId(), c.getName(),c.getExperience(),c.getLevel(),c.getEvolutionPoints(),c.getGeneticsPoints(),c.getUniqueAbilityDecisionsJson(),c.isClosed(),c.getAttributesJson(),c.getGeneticsJson(),c.getCreationMode(),c.getRace(),c.isEinherjer(),c.isAwakened(),c.getEinherjerOrigin(),c.getStartingAge(),c.getAwakeningAge(),c.getSheetAge(),c.getSelectedMajorAttributesJson(),c.getCreationWizardState(), minorValues.findByCharacterId(c.getId()).stream().map(v->new MinorValueData(v.getDefinitionId(),v.getValue())).toList(), modifiers.findByCharacterId(c.getId()).stream().map(m->new ModifierData(m.getAttributeKey(),m.getName(),m.getExactValue(),m.getSource())).toList(), training.findByCharacterIdOrderByStartAgeAscPriorityAsc(c.getId()).stream().map(t->new TrainingData(t.getType(),t.getName(),t.getStartAge(),t.getEndAge(),t.getPriority(),t.getPrimaryAttribute(),t.getSecondaryAttribute(),t.getTertiaryAttribute(),t.isConcurrent())).toList(), others.findByCharacterIdOrderByNameAsc(c.getId()).stream().map(o->new OtherData(o.getName(),o.getDescription(),o.getLocation(),o.getQuantity(),o.getUnitValue())).toList(), weapons.findByCharacterIdOrderBySlotAsc(c.getId()).stream().map(w->new WeaponData(w.getSlot(),w.getName(),w.getWeaponType(),w.getSize(),w.getRange(),w.getReload(),w.getRate(),w.getDamageVital(),w.getDamageNormal(),w.getDamageLight(),w.getDamageVeryLight(),w.getAim(),w.getAutomaticFire(),w.getCapacity(),w.getLoadedBullets(),w.getCaliber(),w.getExtraRule(),w.getCatalogWeaponId())).toList(), ammunition.findByCharacterIdOrderByCaliberAsc(c.getId()).stream().map(a->new AmmoData(a.getCaliber(),a.getQuantity())).toList(), armor.findByCharacterIdOrderByNameAsc(c.getId()).stream().map(a->new ArmorData(a.getName(),a.getDescription(),a.getSlotsJson())).toList(), shields.findByCharacterIdOrderByNameAsc(c.getId()).stream().map(s->new ShieldData(s.getName(),s.getDescription(),s.getHitPoints())).toList(), physicalShields.findByCharacterIdOrderByNameAsc(c.getId()).stream().map(s->new PhysicalShieldData(s.getName(),s.getDescription(),s.getRd(),s.getArmor(),s.getDefense(),s.getOtherEffects())).toList(), milestones.findByCharacterIdOrderByCreatedAtDesc(c.getId()).stream().map(m->new MilestoneData(m.getLevel(),m.getExperience(),m.getSnapshotJson(),m.getNewBonusesJson(),m.getNewAbilitiesJson(),m.isVisible())).toList()); }
    private DefinitionData definition(MinorAttributeDefinitionEntity d){return new DefinitionData(d.getId(),d.getOwnerCharacterId(),d.getKey(),d.getName(),d.getMaxFormula(),d.getBonusSource(),d.getType());}

    private void replaceCharacter(CharacterEntity target, CharacterData s) { replaceCharacter(target,s,Map.of()); }
    private void replaceCharacter(CharacterEntity target, CharacterData s, Map<String,String> definitionIds) { target.setName(s.name()); target.setExperience(s.experience()); target.setLevel(s.level()); target.setEvolutionPoints(s.evolutionPoints()); target.setGeneticsPoints(s.geneticsPoints()); target.setUniqueAbilityDecisionsJson(s.uniqueAbilityDecisionsJson()); target.setClosed(s.closed()); target.setAttributesJson(s.attributesJson()); target.setGeneticsJson(s.geneticsJson()); target.setCreationMode(s.creationMode()); target.setRace(s.race()); target.setEinherjer(s.einherjer()); target.setAwakened(s.awakened()); target.setEinherjerOrigin(s.einherjerOrigin()); target.setStartingAge(s.startingAge()); target.setAwakeningAge(s.awakeningAge()); target.setSheetAge(s.sheetAge()); target.setSelectedMajorAttributesJson(s.selectedMajorAttributesJson()); target.setCreationWizardState(s.creationWizardState()); target.setImportSourceId(s.sourceId()); target.touch(); characters.save(target); String id=target.getId();
        minorValues.deleteAll(minorValues.findByCharacterId(id)); modifiers.deleteByCharacterId(id); training.deleteByCharacterId(id); others.deleteByCharacterId(id); weapons.deleteAll(weapons.findByCharacterIdOrderBySlotAsc(id)); ammunition.deleteAll(ammunition.findByCharacterIdOrderByCaliberAsc(id)); armor.deleteAll(armor.findByCharacterIdOrderByNameAsc(id)); shields.deleteAll(shields.findByCharacterIdOrderByNameAsc(id)); physicalShields.deleteAll(physicalShields.findByCharacterIdOrderByNameAsc(id)); milestones.deleteByCharacterId(id);
        for(var v:s.minorValues()) minorValues.save(new CharacterMinorAttributeValueEntity(UUID.randomUUID().toString(),id,definitionIds.getOrDefault(v.definitionId(),v.definitionId()),v.value())); for(var m:s.modifiers()) modifiers.save(new CharacterAttributeModifierEntity(UUID.randomUUID().toString(),id,m.attributeKey(),m.name(),m.value(),m.source())); for(var t:s.training()) training.save(new TrainingActivityEntity(UUID.randomUUID().toString(),id,t.type(),t.name(),t.startAge(),t.endAge(),t.priority(),t.primary(),t.secondary(),t.tertiary(),t.concurrent())); for(var o:s.others()) others.save(new OtherInventoryItemEntity(UUID.randomUUID().toString(),id,o.name(),o.description(),o.location(),o.quantity(),o.unitValue())); for(var w:s.weapons()) weapons.save(new WeaponEntity(UUID.randomUUID().toString(),id,w.slot(),w.name(),w.weaponType(),w.size(),w.range(),w.reload(),w.rate(),w.damageVital(),w.damageNormal(),w.damageLight(),w.damageVeryLight(),w.aim(),w.automaticFire(),w.capacity(),w.loadedBullets(),w.caliber(),w.extraRule(),w.catalogWeaponId(),null)); for(var a:s.ammunition()) ammunition.save(new AmmunitionEntity(UUID.randomUUID().toString(),id,a.caliber(),a.quantity())); for(var a:s.armor()) armor.save(new ArmorEntity(UUID.randomUUID().toString(),id,a.name(),a.description(),a.slotsJson(),null)); for(var s0:s.shields()) shields.save(new ShieldEntity(UUID.randomUUID().toString(),id,s0.name(),s0.description(),s0.hitPoints(),null)); for(var p:s.physicalShields()) physicalShields.save(new PhysicalShieldEntity(UUID.randomUUID().toString(),id,p.name(),p.description(),p.rd(),p.armor(),p.defense(),p.otherEffects(),null)); for(var m:s.milestones()) milestones.save(new MilestoneEntity(UUID.randomUUID().toString(),id,m.level(),m.experience(),m.snapshotJson(),m.newBonusesJson(),m.newAbilitiesJson(),m.visible())); }

    public record Archive(int version,String type,String exportedAt,CampaignData campaign,CharacterData character) {}
    public record CampaignData(String name,List<DefinitionData> definitions,List<CharacterData> characters) {}
    public record DefinitionData(String id,String ownerCharacterId,String key,String name,String maxFormula,String bonusSource,String type) {}
    public record CharacterData(String sourceId,String name,int experience,int level,int evolutionPoints,int geneticsPoints,String uniqueAbilityDecisionsJson,boolean closed,String attributesJson,String geneticsJson,String creationMode,String race,boolean einherjer,boolean awakened,String einherjerOrigin,Integer startingAge,Integer awakeningAge,Integer sheetAge,String selectedMajorAttributesJson,String creationWizardState,List<MinorValueData> minorValues,List<ModifierData> modifiers,List<TrainingData> training,List<OtherData> others,List<WeaponData> weapons,List<AmmoData> ammunition,List<ArmorData> armor,List<ShieldData> shields,List<PhysicalShieldData> physicalShields,List<MilestoneData> milestones) {}
    public record MinorValueData(String definitionId,int value) {} public record ModifierData(String attributeKey,String name,BigDecimal value,String source) {} public record TrainingData(String type,String name,int startAge,int endAge,int priority,String primary,String secondary,String tertiary,boolean concurrent) {} public record OtherData(String name,String description,String location,int quantity,BigDecimal unitValue) {} public record WeaponData(String slot,String name,String weaponType,String size,BigDecimal range,BigDecimal reload,String rate,BigDecimal damageVital,BigDecimal damageNormal,BigDecimal damageLight,BigDecimal damageVeryLight,BigDecimal aim,String automaticFire,BigDecimal capacity,BigDecimal loadedBullets,String caliber,String extraRule,String catalogWeaponId) {} public record AmmoData(String caliber,int quantity) {} public record ArmorData(String name,String description,String slotsJson) {} public record ShieldData(String name,String description,int hitPoints) {} public record PhysicalShieldData(String name,String description,int rd,int armor,int defense,String otherEffects) {} public record MilestoneData(int level,int experience,String snapshotJson,String newBonusesJson,String newAbilitiesJson,boolean visible) {}
}