package com.dexm.personajes.application;

import com.dexm.personajes.adapter.in.web.CharacterController.ArmorRequest;
import com.dexm.personajes.adapter.in.web.CharacterController.ShieldRequest;
import com.dexm.personajes.adapter.in.web.CharacterController.PhysicalShieldRequest;
import com.dexm.personajes.adapter.out.persistence.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.*;

@Service
public class ProtectiveEquipmentService {
 private static final Set<String> SLOTS=Set.of("HEAD","BODY","LEGS","ARMS");
 private static final Map<String,String> ZONE_TO_SLOT=Map.of("Vital","HEAD","Cuerpo","BODY","Ligero","LEGS","Muy ligero","ARMS");
 private final CharacterRepository characters; private final ArmorRepository armors; private final ShieldRepository shields; private final ShieldCatalogRepository shieldCatalog; private final PhysicalShieldRepository physicalShields; private final ObjectMapper mapper;
 private final OfficialCatalogService official;
 public ProtectiveEquipmentService(CharacterRepository c,ArmorRepository a,ShieldRepository s,ShieldCatalogRepository sc,PhysicalShieldRepository ps,ObjectMapper m,OfficialCatalogService o){characters=c;armors=a;shields=s;shieldCatalog=sc;physicalShields=ps;mapper=m;official=o;}
 @Transactional(readOnly=true) public List<Map<String,Object>> listArmors(String c){ensure(c);return armors.findByCharacterIdOrderByNameAsc(c).stream().map(this::armorView).toList();}
 @Transactional public Map<String,Object> createArmor(String c,ArmorRequest r){ensure(c); validateArmor(r); String json=write(r.slots()); ensureNoOverlap(c,r.slots(),null); return armorView(armors.save(new ArmorEntity(UUID.randomUUID().toString(),c,r.name().trim(),clean(r.description()),json,clean(r.imageUrl()),clean(r.specialEffect()),clean(r.zone()),decimal(r.defensePenalty()),decimal(r.meleeDefensePenalty()),decimal(r.rangedDefensePenalty()),decimal(r.movementPenalty()))));}
 @Transactional public Map<String,Object> updateArmor(String c,String id,ArmorRequest r){var e=findArmor(c,id);validateArmor(r);ensureNoOverlap(c,r.slots(),id);e.setName(r.name().trim());e.setDescription(clean(r.description()));e.setSlotsJson(write(r.slots()));e.setImageUrl(clean(r.imageUrl()));e.setEffect(clean(r.specialEffect()));e.setZone(clean(r.zone()));e.setDefensePenalty(decimal(r.defensePenalty()));e.setMeleeDefensePenalty(decimal(r.meleeDefensePenalty()));e.setRangedDefensePenalty(decimal(r.rangedDefensePenalty()));e.setMovementPenalty(decimal(r.movementPenalty()));return armorView(armors.save(e));}
 @Transactional public void deleteArmor(String c,String id){armors.delete(findArmor(c,id));}
 @Transactional(readOnly=true) public List<Map<String,Object>> listShields(String c){ensure(c);return shields.findByCharacterIdOrderByNameAsc(c).stream().map(this::shieldView).toList();}
 @Transactional public Map<String,Object> createShield(String c,ShieldRequest r){ensure(c);validateShield(r);if(!shields.findByCharacterIdOrderByNameAsc(c).isEmpty())throw new IllegalStateException("Solo puede haber un escudo activo por personaje");return shieldView(shields.save(new ShieldEntity(UUID.randomUUID().toString(),c,r.name().trim(),clean(r.description()),r.hitPoints(),clean(r.imageUrl()))));}
 @Transactional public Map<String,Object> updateShield(String c,String id,ShieldRequest r){var e=findShield(c,id);validateShield(r);e.setName(r.name().trim());e.setDescription(clean(r.description()));e.setHitPoints(r.hitPoints());e.setImageUrl(clean(r.imageUrl()));return shieldView(shields.save(e));}
 @Transactional public void deleteShield(String c,String id){shields.delete(findShield(c,id));}
 @Transactional(readOnly=true) public List<Map<String,Object>> listPhysicalShields(String c){ensure(c);return physicalShields.findByCharacterIdOrderByNameAsc(c).stream().map(this::physicalShieldView).toList();}
 @Transactional public Map<String,Object> createPhysicalShield(String c,PhysicalShieldRequest r){ensure(c);validatePhysicalShield(r);if(!physicalShields.findByCharacterIdOrderByNameAsc(c).isEmpty())throw new IllegalStateException("Solo puede haber un escudo físico activo por personaje");return physicalShieldView(physicalShields.save(new PhysicalShieldEntity(UUID.randomUUID().toString(),c,r.name().trim(),clean(r.description()),r.rd(),r.armor(),r.defense(),r.movement(),clean(r.otherEffects()),clean(r.imageUrl()),clean(r.size()))));}
 @Transactional public Map<String,Object> updatePhysicalShield(String c,String id,PhysicalShieldRequest r){var e=findPhysicalShield(c,id);validatePhysicalShield(r);e.setName(r.name().trim());e.setDescription(clean(r.description()));e.setRd(r.rd());e.setArmor(r.armor());e.setDefense(r.defense());e.setMovement(r.movement());e.setOtherEffects(clean(r.otherEffects()));e.setImageUrl(clean(r.imageUrl()));e.setSize(clean(r.size()));return physicalShieldView(physicalShields.save(e));}
 @Transactional public void deletePhysicalShield(String c,String id){physicalShields.delete(findPhysicalShield(c,id));}
 @Transactional(readOnly=true) public List<Map<String,Object>> armorCatalog(){return official.armors().stream().map(this::staticArmorView).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> shieldCatalog(){return shieldCatalog.findAll().stream().map(this::shieldCatalogView).toList();}
 @Transactional public Map<String,Object> createShieldCatalog(ShieldRequest r){validateShield(r);return shieldCatalogView(shieldCatalog.save(new ShieldCatalogEntity(UUID.randomUUID().toString(),r.name().trim(),clean(r.description()),r.hitPoints(),clean(r.imageUrl()),false)));}
 @Transactional public Map<String,Object> addArmorCatalog(String catalogId,String c){ensure(c);return addStaticArmor(official.armor(catalogId).orElseThrow(()->new NoSuchElementException("Armadura de catálogo no encontrada")),c);}
 @Transactional public Map<String,Object> addShieldCatalog(String catalogId,String c){ensure(c);var x=shieldCatalog.findById(catalogId).orElseThrow(()->new NoSuchElementException("Escudo de catálogo no encontrado"));if(!shields.findByCharacterIdOrderByNameAsc(c).isEmpty())throw new IllegalStateException("Solo puede haber un escudo activo por personaje");return shieldView(shields.save(new ShieldEntity(UUID.randomUUID().toString(),c,x.getName(),x.getDescription(),x.getHitPoints(),x.getImageUrl())));}
 @Transactional(readOnly=true) public List<Map<String,Object>> physicalShieldCatalog(){return official.physicalShields().stream().map(this::staticPhysicalShieldView).toList();}
 @Transactional public Map<String,Object> addPhysicalShieldCatalog(String catalogId,String c){ensure(c);return addStaticPhysicalShield(official.physicalShield(catalogId).orElseThrow(()->new NoSuchElementException("Escudo físico de catálogo no encontrado")),c);}
 private void validateArmor(ArmorRequest r){if(r==null||r.name()==null||r.name().isBlank()||r.slots()==null||r.slots().isEmpty())throw new IllegalArgumentException("La armadura debe ocupar al menos un hueco");for(var e:r.slots().entrySet()){if(!SLOTS.contains(e.getKey()))throw new IllegalArgumentException("Hueco de armadura no válido");if(e.getValue()==null||e.getValue().getOrDefault("rd",-1)<0||e.getValue().getOrDefault("rd",-1)>999||e.getValue().getOrDefault("armor",-1)<0||e.getValue().getOrDefault("armor",-1)>9999)throw new IllegalArgumentException("RD debe estar entre 0 y 999 y Armadura entre 0 y 9999");}}
 private void validateShield(ShieldRequest r){if(r==null||r.name()==null||r.name().isBlank()||r.hitPoints()<0)throw new IllegalArgumentException("El escudo requiere nombre y PV no negativos");}
 private void validatePhysicalShield(PhysicalShieldRequest r){if(r==null||r.name()==null||r.name().isBlank()||r.rd()<0||r.rd()>999||r.armor()<0||r.armor()>9999||r.movement()>0||r.movement()<-999)throw new IllegalArgumentException("El escudo requiere nombre, RD entre 0 y 999 y Armadura entre 0 y 9999");if(r.size()!=null&&!r.size().isBlank()&&!Set.of("Pequeño","Mediano","Grande").contains(r.size().trim()))throw new IllegalArgumentException("Tamaño de escudo no válido");}
 private void ensureNoOverlap(String c,Map<String,Map<String,Integer>> wanted,String own){Set<String> occupied=new HashSet<>();for(var e:armors.findByCharacterIdOrderByNameAsc(c)){if(!e.getId().equals(own))occupied.addAll(read(e.getSlotsJson()).keySet());}for(String slot:wanted.keySet())if(occupied.contains(slot))throw new IllegalStateException("El hueco de armadura ya está ocupado: "+slot);}
 private ArmorEntity findArmor(String c,String id){ensure(c);return armors.findByIdAndCharacterId(id,c).orElseThrow(()->new NoSuchElementException("Armadura no encontrada"));} private ShieldEntity findShield(String c,String id){ensure(c);return shields.findByIdAndCharacterId(id,c).orElseThrow(()->new NoSuchElementException("Escudo no encontrado"));} private void ensure(String c){if(!characters.existsById(c))throw new NoSuchElementException("Personaje no encontrado");}
 private PhysicalShieldEntity findPhysicalShield(String c,String id){ensure(c);return physicalShields.findByIdAndCharacterId(id,c).orElseThrow(()->new NoSuchElementException("Escudo físico no encontrado"));}
 private BigDecimal decimal(BigDecimal value){return value==null?BigDecimal.ZERO:value.max(BigDecimal.ZERO);}
 private BigDecimal decimal(JsonNode value){return value!=null&&value.isNumber()?value.decimalValue():BigDecimal.ZERO;}
 private String write(Object v){try{return mapper.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("Valores de armadura no válidos",e);}} private Map<String,Map<String,Integer>> read(String v){try{return mapper.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException("Datos de armadura corruptos",e);}} private String clean(String v){return v==null||v.isBlank()?null:v.trim();}
 private Map<String,Object> armorView(ArmorEntity e){var m=new LinkedHashMap<String,Object>();m.put("id",e.getId());m.put("name",e.getName());m.put("description",e.getDescription());m.put("specialEffect",e.getEffect());m.put("defensePenalty",e.getDefensePenalty());m.put("meleeDefensePenalty",e.getMeleeDefensePenalty());m.put("rangedDefensePenalty",e.getRangedDefensePenalty());m.put("movementPenalty",e.getMovementPenalty());m.put("zone",e.getZone());var s=read(e.getSlotsJson());m.put("slots",s.keySet());m.put("rdBySlot",s.entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey,x->x.getValue().get("rd"))));m.put("armorBySlot",s.entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey,x->x.getValue().get("armor"))));m.put("imageUrl",e.getImageUrl());return m;}
 private Map<String,Object> shieldView(ShieldEntity e){var m=new LinkedHashMap<String,Object>();m.put("id",e.getId());m.put("name",e.getName());m.put("description",e.getDescription());m.put("hitPoints",e.getHitPoints());m.put("imageUrl",e.getImageUrl());return m;} private Map<String,Object> shieldCatalogView(ShieldCatalogEntity e){var m=shieldView(new ShieldEntity(e.getId(),"",e.getName(),e.getDescription(),e.getHitPoints(),e.getImageUrl()));m.put("official",e.isOfficial());return m;}
 private Map<String,Object> physicalShieldView(PhysicalShieldEntity e){var m=new LinkedHashMap<String,Object>();m.put("id",e.getId());m.put("name",e.getName());m.put("description",e.getDescription());m.put("rd",e.getRd());m.put("armor",e.getArmor());m.put("defense",e.getDefense());m.put("movement",e.getMovement());m.put("otherEffects",e.getOtherEffects());m.put("imageUrl",e.getImageUrl());m.put("size",e.getSize());return m;}
 private Map<String,Object> staticArmorView(JsonNode n){Map<String,Map<String,Integer>> slots=staticArmorSlots(n);String slotsJson=write(slots);var m=new LinkedHashMap<String,Object>(armorView(new ArmorEntity(n.path("id").asText(),"",n.path("name").asText(),n.path("description").asText(null),slotsJson,n.path("imageUrl").asText(null),n.path("specialEffect").asText(null),n.path("zone").asText(null),decimal(n.path("defensePenalty")),decimal(n.path("meleeDefensePenalty")),decimal(n.path("rangedDefensePenalty")),decimal(n.path("movementPenalty")))));m.put("official",true);return m;}
 private Map<String,Object> addStaticArmor(JsonNode n,String c){Map<String,Map<String,Integer>> slots=staticArmorSlots(n);ensureNoOverlap(c,slots,null);return armorView(armors.save(new ArmorEntity(UUID.randomUUID().toString(),c,n.path("name").asText(),n.path("description").asText(null),write(slots),n.path("imageUrl").asText(null),n.path("specialEffect").asText(null),n.path("zone").asText(null),decimal(n.path("defensePenalty")),decimal(n.path("meleeDefensePenalty")),decimal(n.path("rangedDefensePenalty")),decimal(n.path("movementPenalty")))));}
 private Map<String,Map<String,Integer>> staticArmorSlots(JsonNode n){if(n.has("zones")){return mapper.convertValue(n.path("zones"),new TypeReference<>(){});}String slot=n.path("slot").asText();if(slot.isBlank())slot=ZONE_TO_SLOT.getOrDefault(n.path("zone").asText(),"BODY");return Map.of(slot,Map.of("rd",n.path("rd").asInt(),"armor",n.path("armor").asInt()));}
 private Map<String,Object> staticPhysicalShieldView(JsonNode n){var m=new LinkedHashMap<String,Object>();m.put("id",n.path("id").asText());m.put("name",n.path("name").asText());m.put("description",n.path("description").asText(null));m.put("rd",n.path("rd").asInt());m.put("defense",n.path("defense").asInt());m.put("movement",n.path("movement").asInt());m.put("imageUrl",n.path("imageUrl").asText(null));m.put("official",true);return m;}
 private Map<String,Object> addStaticPhysicalShield(JsonNode n,String c){if(!physicalShields.findByCharacterIdOrderByNameAsc(c).isEmpty())throw new IllegalStateException("Solo puede haber un escudo físico activo por personaje");return physicalShieldView(physicalShields.save(new PhysicalShieldEntity(UUID.randomUUID().toString(),c,n.path("name").asText(),n.path("description").asText(null),n.path("rd").asInt(),n.path("armor").asInt(),n.path("defense").asInt(),n.path("movement").asInt(),n.path("otherEffects").asText(null),n.path("imageUrl").asText(null),n.path("size").asText(null))));}
}
