server:
  port: ${SERVER_PORT:8084}
  servlet:
    session:
      cookie:
        name: DEXM_SESSION
spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/dexm_personajes}
    username: ${DB_USERNAME:dexm}
    password: ${DB_PASSWORD:XXXX}
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  flyway.enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:XXXX-ssehf8iobicne0n2jdnvq9d85dbgu6ke.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: ${app.security.frontend-url}login/oauth2/code/{registrationId}
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent"
app:
  security:
    admin-emails: ${APP_SECURITY_ADMIN_EMAILS:albertinizao@gmail.com}
    frontend-url: ${APP_SECURITY_FRONTEND_URL:http://localhost:5177/}
